package pembayaran.uang.sekolah;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pembayarantunggakan.java
 *
 * Created on 07 Jun 14, 10:14:50
 */
/**
 *
 * @author ivan
 */
public final class pembayarantunggakan extends javax.swing.JFrame {
    private final DefaultTableModel model;

    /** Creates new form pembayarantunggakan */
    public pembayarantunggakan() {
        initComponents();
         model = new DefaultTableModel();
       tabeltunggakan.setModel(model);
        model.addColumn("nis");
        model.addColumn("nama_pembayar");
        model.addColumn("jenis_tunggakan");
        model.addColumn("tanggal_pembayaran");
        model.addColumn("jumlah_pembayaran");
        model.addColumn("sisa_pembayaran");
      
        loadData();
    
    }
        public void loadData() {

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = (Connection) KoneksiDatabase.getKoneksi();
            Statement s = (Statement) c.createStatement();

            String sql = "SELECT * FROM pembayaran_tunggakan";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("nis");
                o[1] = r.getString("nama_pembayar");
                o[2] = r.getString("jenis_tunggakan");
                o[3] = r.getString("tanggal_pembayaran");
                o[4] = r.getString("jumlah_pembayaran");
                o[5] = r.getString("sisa_pembayaran");
                
                model.addRow(o);
      }

            r.close();
            s.close();
        } catch (SQLException e) {

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputnis = new javax.swing.JTextField();
        inputnamapembayar = new javax.swing.JTextField();
        inputjenistunggakan = new javax.swing.JTextField();
        inputjumlahpembayaran = new javax.swing.JTextField();
        inputsisapembayaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltunggakan = new javax.swing.JTable();
        inputtanggalpembayaran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel1.setText("PEMBAYARAN TUNGGAKAN");

        jLabel2.setText("NIS");

        jLabel3.setText("NAMA PEMBAYAR");

        jLabel4.setText("JENIS TUNGGAKAN");

        jLabel5.setText("TANGGAL PEMBAYARAN");

        jLabel6.setText("JUMLAH PEMBAYARAN");

        jLabel7.setText("SISA PEMBAYARAN");

        inputnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnisActionPerformed(evt);
            }
        });

        inputjumlahpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputjumlahpembayaranActionPerformed(evt);
            }
        });

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabeltunggakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA PEMBAYAR", "JENIS TUNGGAKAN", "TANGGAL PEMBAYARAN", "JUMLAH PEMBAYARAN", "SISA PEMBAYARAN"
            }
        ));
        tabeltunggakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltunggakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeltunggakan);

        inputtanggalpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtanggalpembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inputsisapembayaran, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputjumlahpembayaran, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputtanggalpembayaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                    .addComponent(inputjenistunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputnamapembayar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputnis, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton2)
                                .addGap(43, 43, 43)
                                .addComponent(jButton3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(597, 597, 597))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(inputtanggalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(inputnamapembayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(inputjenistunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputjumlahpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inputsisapembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnisActionPerformed

    private void inputjumlahpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputjumlahpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputjumlahpembayaranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nis = inputnis.getText();
        String nama_pembayar = inputnamapembayar.getText();
        String jenis_tunggakan = inputjenistunggakan.getText();
        String tanggal_pembayaran = inputtanggalpembayaran.getText();
        String jumlah_pembayaran = inputjumlahpembayaran.getText();
        String sisa_pembayaran = inputsisapembayaran.getText();
                try {
            Connection c = (Connection) KoneksiDatabase.getKoneksi();

            String sql = "INSERT INTO pembayaran_tunggakan VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);

            p.setString(1, nis);
            p.setString(2, nama_pembayar);
            p.setString(3, jenis_tunggakan);
            p.setString(4, tanggal_pembayaran);
            p.setString(5, jumlah_pembayaran);
            p.setString(6, sisa_pembayaran);
           

            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        } finally {
            loadData();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     int i = tabeltunggakan.getSelectedRow();
        if (i == -1) {
            return;
        }
        String nis = (String) tabeltunggakan.getValueAt(i, 0);
        try {
            Connection c = (Connection) KoneksiDatabase.getKoneksi();
            String sql = "DELETE FROM pembayaran_tunggakan WHERE nis = ?";
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);

            p.setString(1, nis);

            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println("Terjadi Error");
        } finally {
            loadData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabeltunggakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltunggakanMouseClicked
    int i = tabeltunggakan.getSelectedRow();
        if(i == -1){
            return;}
        String nis = (String) model.getValueAt(i, 0);
        inputnis.setText(nis);
        
        String nama_pembayar = (String) model.getValueAt(i, 1);
        inputnamapembayar.setText(nama_pembayar);
        
        String jenis_tunggakan = (String) model.getValueAt(i, 2);
        inputjenistunggakan.setText(jenis_tunggakan);
        
        String tanggal_pembayaran = (String)model.getValueAt(i, 3);
        inputtanggalpembayaran.setText(tanggal_pembayaran);
        
        String jumlah_pembayaran = (String) model.getValueAt(i, 4);
        inputjumlahpembayaran.setText(jumlah_pembayaran);
                
        String sisa_pembayaran = (String)model.getValueAt(i, 5);
        inputsisapembayaran.setText(sisa_pembayaran);
    }//GEN-LAST:event_tabeltunggakanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int i = tabeltunggakan.getSelectedRow();
        if (i == -1) {
            return;
        
        }
        String nis = (String) model.getValueAt(i, 0);
        String nama_pembayar = inputnamapembayar.getText();
        String jenis_tunggakan = inputjenistunggakan.getText();
        String tanggal_pembayaran = inputtanggalpembayaran.getText();
        String jumlah_pembayaran = inputjumlahpembayaran.getText();
        String sisa_pembayaran = inputsisapembayaran.getText();
       
        
        try {
            Connection c = (Connection) KoneksiDatabase.getKoneksi();
            String sql = "UPDATE pembayaran_tunggakan SET nama_pembayar  = ?, jenis_tunggakan = ?, tanggal_pembayaran = ?, jumlah_pembayaran= ?, sisa_pemabayaran= ? WHERE nis= ?";
            
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);

            
            p.setString(1, nis);
            p.setString(2, nama_pembayar);
            p.setString(2, jenis_tunggakan);
            p.setString(3, tanggal_pembayaran);
            p.setString(4, jumlah_pembayaran);
            p.setString(5, sisa_pembayaran);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");

        } finally {
            loadData();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inputtanggalpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtanggalpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputtanggalpembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pembayarantunggakan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputjenistunggakan;
    private javax.swing.JTextField inputjumlahpembayaran;
    private javax.swing.JTextField inputnamapembayar;
    private javax.swing.JTextField inputnis;
    private javax.swing.JTextField inputsisapembayaran;
    private javax.swing.JTextField inputtanggalpembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeltunggakan;
    // End of variables declaration//GEN-END:variables
}
